// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGXN5DIF3JvDjjrLL-hqSfJUOKM3wdcow',
    appId: '1:599053543859:android:48fd20ecb3688f6bc203c6',
    messagingSenderId: '599053543859',
    projectId: 'travelclothingclub',
    storageBucket: 'travelclothingclub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKEYnYxWQwReTcoCbwLgy_g3ktF4ws-sk',
    appId: '1:599053543859:ios:621ccdba7c9374a8c203c6',
    messagingSenderId: '599053543859',
    projectId: 'travelclothingclub',
    storageBucket: 'travelclothingclub.firebasestorage.app',
    androidClientId: '599053543859-3g6tdb5cqbenij24blih9fh31n7s245t.apps.googleusercontent.com',
    iosClientId: '599053543859-tjanjprg36p9iugvt8k84hea4jdlj0hn.apps.googleusercontent.com',
    iosBundleId: 'travelclothingclub.com',
  );
}
